export const lightTheme = {
  page: {
    fontFamily: "Inter, system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial",
    background: '#f7f8fb',
    color: '#0f172a',
    minHeight: '100vh',
    padding: '48px 16px',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100vw',
  } as const,
  card: {
    background: '#ffffff',
    borderRadius: 12,
    boxShadow: '0 6px 18px rgba(16,24,40,0.08)',
    padding: 24,
    width: '100%',
    maxWidth: 'min(900px, 95vw)',
    boxSizing: 'border-box',
  } as const,
  header: { marginBottom: 16 } as const,
  title: { fontSize: 20, margin: 0 } as const,
  form: { display: 'grid', gap: 12 } as const,
  input: {
    height: 40,
    padding: '8px 12px',
    borderRadius: 8,
    border: '1px solid #e6edf3',
    background: '#fff',
    color: '#0f172a',
    outline: 'none',
    fontSize: 14,
    width: '100%',
    boxSizing: 'border-box',
  } as const,
  button: {
    height: 40,
    borderRadius: 8,
    border: 'none',
    background: '#0b69ff',
    color: '#fff',
    fontWeight: 600,
    cursor: 'pointer',
    padding: '0 12px',
  } as const,
  subtleButton: {
    height: 40,
    borderRadius: 8,
    border: '1px solid #e6edf3',
    background: '#fff',
    color: '#0f172a',
    cursor: 'pointer',
    padding: '0 12px',
  } as const,
  footer: { marginTop: 12, fontSize: 13, color: '#475569' } as const,
  alert: { padding: 10, borderRadius: 8, fontSize: 13 } as const,
}

export default lightTheme
